[general]
import = [
  "~/.config/alacritty/themes/catppuccin.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrains Mono Nerd Font" }
italic = { family = "JetBrainsMono Nerd Font" }
size = 14
