; Author: Krishal
; Github: ikrsx
; Credit: github/catppuccin (for themeing)
; Description: Configuration file for fuzzel application launcher.

; Basic configurations.
[main]
dpi-aware = yes
font = "JetBrainsMono Nerd Font:size=7"
icons-enabled = no

; Set Catppuccin Mocha colors.
[colors]
background=1e1e2edd
text=cdd6f4ff
prompt=bac2deff
placeholder=7f849cff
input=cdd6f4ff
match=cba6f7ff
selection=585b70ff
selection-text=cdd6f4ff
selection-match=cba6f7ff
counter=7f849cff
border=cba6f7ff
