# Author: Krishal
# Github: ikrsx
# Credit: github.com/catppuccin (for theming)
# Description: Configuration file for hyprlock lockscreen.

# VARIABLES
$font = JetBrainsMono Nerd Font

general {
    hide_cursor = false
}

# LOCKSCREEN BACKGROUND
background {
    monitor =
    path = screenshot
    blur_passes = 6
}

# INPUT BOX
input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 0
    inner_color = rgba(108, 112, 134, 0.25)

    outer_color = rgba(0, 0, 0, 0.0)
    check_color = rgba(249, 226, 175, 0.25)
    fail_color = rgba(243, 139, 168, 0.25)

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL

    position = 0, -20
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME
    font_size = 90
    font_family = JetBrainsMono Nerd Font ExtraBold

    position = 0, 150
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 18
    font_family = $font

    position = 0, 50
    halign = center
    valign = center
}
