# Author: Krishal
# Github: ikrsx
# Description: Configuration file for hyprpaper wallpaper manager.

wallpaper {
    monitor = eDP-1
    path = ~/.config/hypr/wallpapers/clouds_night.jpg
    fit_mode = cover
}
