# Author: Krishal
# Github: ikrsx
# Credits: github.com/catppuccin (for theming)
# Description: Configuration file for tmux terminal multiplexer.

# Terminal coloring settings.
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"

# Enable some features.
set -g mouse on
set -g set-clipboard on

# Setting custom prefix key.
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

# Setting custom splitting windows bindings.
unbind %
unbind '"'
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

# Setting Vim-style pane navigation.
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Setting binding for reloading tmux config.
unbind r
bind r source-file $HOME/.config/tmux/tmux.conf

# Setting pane switching without prefix keys.
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Start indexing at 1.
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Setting arrow-keys to switch between windows.
bind -n S-Left previous-window
bind -n S-Right next-window

# Setting Alt key to switch between windows.
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Enabling Vim-style yanking.
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane

# Declare color pallete.
mauve="#cba6f7"
red="#f38ba8"
yellow="#f9e2af"
blue="#89b4fa"
white="#cdd6f4"
black="#1e1e2e"
grey="#585b70"

# Place bars on the top of the screen.
set -g status-position top

# Set the size of session name.
set -g status-left-length 100

# Style the status bar.
set -g status-style "fg=${white},bg=default"
set -g status-left "#[fg=${blue},bold]  #S #[fg=${grey},nobold]|"
set -g status-right ""

# Style the window indicators.
set -g window-status-current-format "#[fg=${yellow},bold] #I.#W"
set -g window-status-format "#[fg=${grey}] #I"

# Style the message box.
set -g message-style "fg=${white},bg=default"

# Style the mode window.
set -g mode-style "fg=${black},bold,bg=${mauve}"

# Style the window seperator.
set -g pane-active-border-style "fg=${mauve}"
